### ISSUE TITLE
Add function to withdraw LINK

### ISSUE THREAD

**Issue by kPatch** [PizzaDAO/pizza-smartcontract#57]
## Overview
LINK will be deposited to the contract to fund VRF. 
A function to withdraw the LINK when necessary should be defined, to be used once pizzas have been issued.

https://github.com/PizzaDAO/pizza-smartcontract/blob/featurn/chainlinkVRFPOC/contracts/token/RandomConsumer.sol

**Comment by johhonn** [comment]
This has been implemented

**Comment by CryptoSpaces** [comment]
@johhonn Where though? Could you create a PR?
