### ISSUE TITLE
VRF should fallback to original implementation

### ISSUE THREAD

**Issue by AddressXception** [PizzaDAO/pizza-smartcontract#60]
some networks we test on do not have a VRF implementation so our function needs to fall back to the original.  also, the original should include the difficulty in the hash calculation so that it is more secure.

https://github.com/PizzaDAO/pizza-smartcontract/blob/featurn/chainlinkVRFPOC/contracts/token/RandomConsumer.sol

**Comment by antron3000** [comment]
which networks will we deploy on other than ETH mainnet? where randomess matters?
